Sample script for finding failed jobs in View using Zowe CLI.
BroadcomMFD/broadcom-product-scripts pull request #56
Opened 2024-02-14 14:16 UTC by jan-podrouzek-brcm

New sample script for finding failed jobs in View using Zowe CLI and Web Viewer.

2024-02-14 14:35 UTC, adam-wolfe approved these changes
Looks good to me. Thanks @jan-podrouzek-brcm

2024-02-14 16:12 UTC, bisvo01 requested changes

2024-02-14 16:12 UTC, bisvo01 commented on output-management/web-viewer/README.md
> +  locate failed jobs and optinally download and search within their content.
```suggestion
  locate failed jobs and optionally download and search within their content.
```
possibly also 
> download **them** and search within their content

2024-02-14 16:12 UTC, bisvo01 commented on output-management/web-viewer/find-failed-jobs/README.md
> +The script also support job filtering based on:
```suggestion
The script also supports job filtering based on:
```

2024-02-14 16:12 UTC, bisvo01 commented on output-management/web-viewer/README.md
> +- [Find Failed Jobs](find-failed-jobs) - A bash script leveraging the View plug-in for Zowe CLI to
```suggestion
- [Find Failed Jobs](find-failed-jobs) - A bash script leveraging the View Plug-in for Zowe CLI to
```
consistency with [official naming](https://techdocs.broadcom.com/us/en/ca-mainframe-software/devops/ca-brightside/3-0/zowe-cli/available-cli-plug-ins/ca-view-plug-in-for-zowe-cli.html) that is already used in the other README file, possibly also applies to several places within the script itself

2024-02-15 11:42 UTC, bisvo01 approved these changes

2024-02-15 11:49 UTC, merged