Package shipping scrpting examples
BroadcomMFD/broadcom-product-scripts pull request #81
Opened 2024-06-19 21:28 UTC by waljo11

**Description of changes**

2024-06-19 21:29 UTC, waljo11 commented
Endevor Package shipping example and alternative models and skeletons

2024-06-21 13:30 UTC, adam-wolfe requested changes
Hi @waljo11, PR looks mostly good, I noted a few items that should be replaced.

2024-06-21 13:30 UTC, adam-wolfe commented on endevor/Package-Shipping-Model-and-Script-Examples/ISPF variables.txt
> +VDDCUSER V   WALJO11
Replace user ID

2024-06-21 13:30 UTC, adam-wolfe commented on endevor/Package-Shipping-Model-and-Script-Examples/ISPF variables.txt
> +VDDXNODE V   10.175.81.10
Replace with generic IP address

2024-06-21 13:30 UTC, adam-wolfe commented on endevor/Package-Shipping-Model-and-Script-Examples/C1BMXIN.skl
> +//*----------------------- WALJO11.CLIST.TSO06(ENBPIU00) --------------
Replace user ID

2024-06-25 20:12 UTC, adam-wolfe approved these changes
Looks good. Thanks @waljo11.

2024-06-26 14:44 UTC, merged